# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4bac420c0ef4772b8793a3f5d937b302dab5a49f5e927c228e6a899a4e288dbdd79841c39a3d1d919643a8379afd8a18285e9e5fa853bdf85e57f6a182191830

test:
  secret_key_base: c7c27f14a3f236e72089bec8bd37ee474a77a9e992d803e56591768095623daee0e610836f359965e9aeb5822f51103c031fbcae97046fc660e5f8084efe699c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
